### ISSUE TITLE
Entering `-` as query crashes the CLI app

### ISSUE THREAD

**Issue by ramalho** [standupdev/gimel#1]
Demo:

```
$ ./gimel -
** (MatchError) no match of right hand side value: []
    (gimel) lib/gimel.ex:63: Gimel.search/2
    (gimel) lib/gimel/CLI.ex:18: Gimel.CLI.repl/3
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by ramalho** [comment]
fixed by ramalho@fefe1ad
